# Generated by Django 4.0.5 on 2022-06-30 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_metadata_studentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
