# Generated by Django 4.0.5 on 2022-06-30 03:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0009_alter_batch_assigned_faculty_member'),
        ('users', '0007_remove_studentprofile_users_stude_batch_i_378aba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_batch', to='departments.batch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
