# Generated by Django 4.0.5 on 2022-07-03 12:49

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_alter_batch_degree'),
        ('users', '0009_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=modelcluster.fields.ParentalKey(limit_choices_to={'role__name': 'Student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_batch', to='departments.batch'),
        ),
    ]
