# Generated by Django 4.0.5 on 2022-07-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
    ]
