# Generated by Django 4.0.5 on 2022-07-13 00:56

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_featured_title_studenthomepage_announcement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthomepage',
            options={'verbose_name': 'Student HomePage'},
        ),
        migrations.AlterField(
            model_name='studenthomepage',
            name='welcome_title',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
