# Generated by Django 4.0.5 on 2022-08-31 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0009_batchuploadresult_alter_studentrecords_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_alter_studenthomepage_institute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('data', models.JSONField(default=students.models.data_default)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_record', to='custom_dashboard.studentrecords')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_record_result', to='custom_dashboard.batchuploadresult')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'Student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Record',
                'verbose_name_plural': 'Student Records',
            },
        ),
    ]
