# Generated by Django 4.0.5 on 2022-09-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='retake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='year_gap',
            field=models.BooleanField(default=False),
        ),
    ]
