# Generated by Django 4.0.8 on 2022-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentrecord_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='term',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('retake', 'year', 'term', 'level')},
        ),
    ]
