# Generated by Django 4.0.8 on 2022-11-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_studentrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together=set(),
        ),
    ]
