# Generated by Django 4.0.5 on 2022-06-25 04:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_degree'),
        ('departments', '0003_batch_assigned_faculty_member'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('department', 'name')},
        ),
        migrations.AddField(
            model_name='batch',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.degree'),
        ),
        migrations.AddField(
            model_name='batch',
            name='suffix',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Numbers only', regex='^[0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='custom_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='code',
        ),
    ]
