# Generated by Django 4.0.5 on 2022-06-30 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0008_alter_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assigned_faculty_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Faculty Member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
