# Generated by Django 4.1 on 2022-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0013_alter_batch_unique_together_batch_collection_key_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="alternative_name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
