# Generated by Django 4.1 on 2022-09-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("departments", "0014_department_alternative_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="collection_key",
        ),
        migrations.RemoveField(
            model_name="department",
            name="collection_key",
        ),
        migrations.AddField(
            model_name="batch",
            name="collection",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_collection",
                to="wagtailcore.collection",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="collection",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_collection",
                to="wagtailcore.collection",
            ),
        ),
    ]
