# Generated by Django 4.0.5 on 2022-09-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_remove_batch_collection_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchyear',
            options={'ordering': ('year_to',), 'verbose_name': 'Batch Year', 'verbose_name_plural': 'Batch Years'},
        ),
    ]
