# Generated by Django 4.0.5 on 2022-09-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_alter_batchyear_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='level',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together={('batch', 'level', 'year_from', 'year_to')},
        ),
    ]
