# Generated by Django 4.0.5 on 2022-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0017_alter_batchyear_unique_together_batchyear_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchyear',
            name='level',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1),
        ),
    ]
