# Generated by Django 4.0.5 on 2022-09-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0018_alter_batchyear_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchyear',
            options={'ordering': ('batch', 'level', 'year_to'), 'verbose_name': 'Batch Year', 'verbose_name_plural': 'Batch Years'},
        ),
    ]
