# Generated by Django 4.0.5 on 2022-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0019_alter_batchyear_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='year',
            field=models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], default=2022),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term')], default='First Term', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('department', 'name', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together={('batch', 'level', 'term', 'year_to')},
        ),
    ]
