# Generated by Django 4.0.5 on 2022-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0020_alter_batch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchyear',
            name='term',
            field=models.CharField(choices=[('I', 'First Term'), ('II', 'Second Term')], default='I', max_length=50),
        ),
    ]
