# Generated by Django 4.0.5 on 2022-09-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0021_alter_batchyear_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchyear',
            options={'ordering': ('batch', 'level', 'year_to'), 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batchyear',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_department', to='departments.department'),
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together={('department', 'level', 'term', 'year_to')},
        ),
    ]
