# Generated by Django 4.0.5 on 2022-09-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_alter_batchyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'get_latest_by': 'created_at', 'ordering': ('name',), 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterUniqueTogether(
            name='batchyear',
            unique_together={('batch', 'level', 'term', 'year_to')},
        ),
    ]
