# Generated by Django 4.0.5 on 2022-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0023_alter_batch_options_alter_batchyear_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchyear',
            name='term',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II')], default='I', max_length=50),
        ),
    ]
