# Generated by Django 4.0.5 on 2022-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0024_alter_batchyear_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchyear',
            name='term',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II')], default=1),
        ),
    ]
