# Generated by Django 4.0.5 on 2022-07-03 21:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('institutes', '0002_degree'),
        ('custom_dashboard', '0002_studentrecords_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentrecords',
            options={'verbose_name': 'Batch Record', 'verbose_name_plural': 'Batch Records'},
        ),
        migrations.RemoveField(
            model_name='studentrecords',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='studentrecords',
            name='link_document',
        ),
        migrations.RemoveField(
            model_name='studentrecords',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentrecords',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentrecords',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='institute',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_student_records', to='institutes.institute'),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('approve_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approve', 'Approve')], default='pending', max_length=50)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('records', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='custom_dashboard.studentrecords')),
            ],
            options={
                'verbose_name': 'Student File',
                'verbose_name_plural': 'Student Files',
            },
        ),
    ]
