# Generated by Django 4.0.5 on 2022-07-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_dashboard', '0003_alter_studentrecords_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='approve_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approve', 'Approve')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='assigned_controller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Controller of Exam'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_controller', to=settings.AUTH_USER_MODEL, verbose_name='Controller of Exam'),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='assigned_pr',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Proof Reader of Exam'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proof_reader', to=settings.AUTH_USER_MODEL, verbose_name='Proof Reader of Exam'),
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
