# Generated by Django 4.0.5 on 2022-07-30 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_dashboard', '0006_studentrecords_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
