# Generated by Django 4.0.5 on 2022-07-30 15:57

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0007_studentrecords_timestamp_studentrecords_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='comment',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
