# Generated by Django 4.0.5 on 2022-08-31 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_alter_batch_unique_together_batch_collection_key_and_more'),
        ('custom_dashboard', '0009_batchuploadresult_alter_studentrecords_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='batch_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_record_year_batch', to='departments.batchyear', verbose_name='Year batch'),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approve', 'Approve'), ('processing', 'Processing'), ('invalid', 'Invalid')], default='processing', max_length=50),
        ),
        migrations.AddField(
            model_name='batchuploadresult',
            name='batch_file',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_student_records', to='custom_dashboard.studentrecords'),
        ),
        migrations.AddField(
            model_name='batchuploadresult',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__name': 'Student'}, related_name='batch_upload_result', to=settings.AUTH_USER_MODEL),
        ),
    ]
