# Generated by Django 4.1 on 2022-09-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_dashboard", "0011_batchuploadresult_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchuploadresult",
            name="certificates",
            field=models.CharField(
                choices=[("Provisional", "Provisional")],
                default="Provisional",
                max_length=50,
            ),
        ),
    ]
