# Generated by Django 4.1 on 2022-09-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_remove_batch_collection_key_and_more'),
        ('custom_dashboard', '0013_batchuploadresult_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term')], default='First Term', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecords',
            unique_together={('batch_year', 'term')},
        ),
    ]
