# Generated by Django 4.0.5 on 2022-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0019_batchuploadresult_batch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023)], null=True),
        ),
    ]
