# Generated by Django 4.0.5 on 2022-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0024_alter_studentrecords_term_alter_studentrecords_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='term',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II')], default=1),
        ),
    ]
