# Generated by Django 4.0.5 on 2022-07-30 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0005_customdocument_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='code',
            field=models.CharField(max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='Alphanumeric only', regex='^[a-zA-Z0-9]+$')]),
        ),
    ]
