# Generated by Django 4.1 on 2022-09-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        (
            "institutes",
            "0007_alter_institute_unique_together_customdocument_batch_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituteCollections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="wagtailcore.collection"
                    ),
                ),
                (
                    "institute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intitute_collections",
                        to="institutes.institute",
                    ),
                ),
            ],
        ),
    ]
