# Generated by Django 4.1 on 2022-09-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutes", "0009_remove_institute_collection_key_institute_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institute",
            name="name",
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
