# Generated by Django 4.0.5 on 2022-07-07 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_customdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdocument',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institute_documents', to='institutes.institute'),
        ),
    ]
