# Generated by Django 4.0.5 on 2022-07-08 20:11

from django.db import migrations, models
import institutes.models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_alter_customdocument_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='data',
            field=models.JSONField(blank=True, default=institutes.models.data_default, null=True),
        ),
    ]
