# Generated by Django 4.0.5 on 2022-08-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_alter_batch_unique_together_batch_collection_key_and_more'),
        ('institutes', '0006_alter_degree_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_documents', to='departments.batchyear'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_documents', to='departments.department'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='collection_key',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
