# Generated by Django 4.1 on 2022-09-01 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("institutes", "0008_institutecollections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institute",
            name="collection_key",
        ),
        migrations.AddField(
            model_name="institute",
            name="collection",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_key",
                to="wagtailcore.collection",
            ),
        ),
    ]
