# Generated by Django 4.0.8 on 2022-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0010_alter_institute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='has_task',
            field=models.BooleanField(default=False),
        ),
    ]
