# Generated by Django 4.0.5 on 2022-06-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_id_suffix_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_suffix',
            new_name='suffix',
        ),
    ]
