# Generated by Django 4.0.5 on 2022-06-28 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_batch_unique_together_batch_year_and_more'),
        ('users', '0003_rename_id_suffix_customuser_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='metadata',
            field=models.JSONField(blank=True, default=users.models.meta_default, null=True),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.batch')),
                ('user', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['batch'], name='users_stude_batch_i_378aba_idx'),
        ),
    ]
