# Generated by Django 4.0.5 on 2022-06-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentprofile',
            name='users_stude_batch_i_378aba_idx',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='batch',
        ),
    ]
