# Generated by Django 4.0.5 on 2022-07-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_batch'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
