# Generated by Django 4.0.5 on 2022-09-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0022_alter_batchyear_options_and_more'),
        ('users', '0019_alter_customuser_options_customuser_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_batch', to='departments.batch'),
        ),
    ]
