# Generated by Django 4.0.5 on 2022-07-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_customdocument'),
        ('custom_dashboard', '0004_studentrecords_approve_at_studentrecords_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='link_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutes.customdocument'),
        ),
    ]
