# Generated by Django 4.0.5 on 2022-07-06 20:27

import custom_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0005_alter_studentrecords_link_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='data',
            field=models.JSONField(default=custom_dashboard.models.data_default),
        ),
    ]
