# Generated by Django 4.0.5 on 2022-08-31 16:56

import custom_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0008_studentrecords_publish_alter_studentrecords_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUploadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('certificates', models.CharField(choices=[('Provisional', 'Provisional'), ('Certificate', 'Certificate')], default='Certificate', max_length=50)),
                ('data', models.JSONField(default=custom_dashboard.models.batch_data)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificate Generator',
            },
        ),
        migrations.AlterModelOptions(
            name='studentrecords',
            options={'verbose_name': 'Student Batch Record', 'verbose_name_plural': 'Student Batch Records'},
        ),
    ]
