# Generated by Django 4.1 on 2022-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_dashboard", "0010_studentrecords_batch_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchuploadresult",
            name="date",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
