# Generated by Django 4.1 on 2022-09-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("custom_dashboard", "0012_alter_batchuploadresult_certificates"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchuploadresult",
            name="collection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
            ),
        ),
    ]
