# Generated by Django 4.0.5 on 2022-09-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_alter_batchyear_options'),
        ('institutes', '0010_alter_institute_name'),
        ('custom_dashboard', '0014_studentrecords_term_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrecords',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentrecords',
            name='batches',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_record_year_batch', to='departments.batchyear', verbose_name='Batches'),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='batch_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentrecords',
            unique_together={('institute', 'batch_year', 'term')},
        ),
    ]
