# Generated by Django 4.0.5 on 2022-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0016_alter_studentrecords_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='batch_year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023)], null=True),
        ),
    ]
