# Generated by Django 4.0.5 on 2022-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0021_alter_studentrecords_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='term',
            field=models.CharField(choices=[('I', 'First Term'), ('II', 'Second Term')], default='I', max_length=50),
        ),
    ]
