# Generated by Django 4.0.5 on 2022-09-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0022_alter_studentrecords_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecords',
            name='batch_year',
        ),
    ]
