# Generated by Django 4.0.5 on 2022-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0024_alter_batchyear_term'),
        ('custom_dashboard', '0023_remove_studentrecords_batch_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecords',
            name='term',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II')], default='I', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecords',
            name='year',
            field=models.IntegerField(choices=[(2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='batchuploadresult',
            unique_together={('batch_file', 'batch_year')},
        ),
    ]
