# Generated by Django 4.0.5 on 2022-09-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_dashboard', '0025_alter_studentrecords_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecords',
            name='exam_held',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], default=1),
        ),
    ]
