# Generated by Django 4.0.5 on 2022-06-27 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutes', '0002_degree'),
        ('departments', '0004_alter_batch_unique_together_batch_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='assigned_faculty_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__name': 'Faculty Member'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batch',
            name='degree',
            field=models.ForeignKey(limit_choices_to={'institute': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.degree'),
        ),
    ]
