# Generated by Django 4.0.5 on 2022-06-28 11:47

from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_degree'),
        ('departments', '0006_alter_batch_unique_together_batch_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.degree'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.IntegerField(choices=[(2022, django_utils.choices.Choice(2022, 'r'))], default=2022),
        ),
    ]
