# Generated by Django 4.0.5 on 2022-07-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_degree'),
        ('departments', '0009_alter_batch_assigned_faculty_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.degree'),
        ),
    ]
