# Generated by Django 4.0.5 on 2022-09-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentrecord_retake_studentrecord_year_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='has_retake',
            field=models.BooleanField(default=False),
        ),
    ]
