# Generated by Django 4.0.8 on 2022-11-03 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_dashboard', '0027_alter_studentrecords_exam_held'),
        ('students', '0011_studentrecord_level_studentrecord_term_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentrecord',
            unique_together={('student', 'record', 'retake', 'year', 'term', 'level')},
        ),
    ]
